modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   displayURL="${curseforge_url}"
   logoFile="${logo_file}"
   #credits="Thanks for this example mod goes to Java"
   authors="${mod_authors}"
   description='''${mod_description}'''
   displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
   modId="neoforge"
   type="required"
   versionRange="${neoforge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   type="required"
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="cloth_config"
   type="required"
   versionRange="${cloth_config_version_range_forge}"
   ordering="NONE"
   side="CLIENT"

[[mixins]]
   config="${mod_id}.mixins.json"

[[mixins]]
   config="${mod_id}-common.mixins.json"